#!/bin/bash

set -o nounset
set -o errexit

DIR=$(pwd)
BUILDDIR=$DIR/build
NGINX_DIR=nginx
NGINX_VERSION=1.7.9

clean () {
    rm -rf build
}

setup_local_directories () {
    if [ ! -d $BUILDDIR ]; then
        mkdir $BUILDDIR > /dev/null 2>&1
    fi

    if [ ! -d "vendor" ]; then
        mkdir vendor > /dev/null 2>&1
    fi
}

install_nginx () {
    if [ ! -d "build/nginx" ]; then
        mkdir $BUILDDIR/$NGINX_DIR > /dev/null 2>&1
        pushd vendor > /dev/null 2>&1

        if [ ! -d "nginx-$NGINX_VERSION" ]; then
            if [ ! -e "nginx-$NGINX_VERSION.tar.gz" ]; then
                curl -s -L -O "http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz"
            fi
            tar xzf "nginx-$NGINX_VERSION.tar.gz"
        fi

        pushd "nginx-$NGINX_VERSION" > /dev/null 2>&1
        ./configure                           \
            --with-debug                      \
            --prefix=$(pwd)/../../build/nginx \
            --conf-path=conf/nginx.conf       \
            --error-log-path=logs/error.log   \
            --http-log-path=logs/access.log   \
            --add-module=../../
        make
        make install
        popd > /dev/null 2>&1
        popd > /dev/null 2>&1
        ln -sf $(pwd)/nginx.conf $(pwd)/build/nginx/conf/nginx.conf
    else
        printf "NGINX already installed\n"
    fi
}

if [[ "$#" -eq 1 ]]; then
    if [[ "$1" == "clean" ]]; then
        clean
    else
        echo "clean is the only option"
    fi
else
    setup_local_directories
    install_nginx
fi
